added frontend tests

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -39,7 +39,7 @@ jobs:
           domain: metasfresh
       - name: run-tests
         run: |
-          docker buildx build -t tests .
+          docker buildx build -f Dockerfile.junit -t tests .
       - name: publish results
         run: |
           docker run --rm -v "$(pwd)/junit:/reports" tests                                                # extracting test results from docker image
@@ -58,15 +58,30 @@ jobs:
           name: junit-logs
           path: junit/**/junit.log
 
-
   frontend:
     runs-on: ubuntu-latest
     needs: [init]
     steps:
       - uses: actions/checkout@v3
-      - name: do-it
+      - uses: testspace-com/setup-testspace@v1
+        with:
+          domain: metasfresh
+      - name: run-tests
         run: |
-          echo 'building...'
+          docker buildx build -f Dockerfile.jest -t tests .
+      - name: publish results
+        run: |
+          docker run --rm -v "$(pwd)/jest:/reports" tests                                                 # extracting test results from docker image
+          testspace "[jest/frontend]jest/jest.xml"                                                        # upload junit xml to testspace 
+          testspace "[jest/frontend]jest/jest.log{$(cat jest/jest.exit-code):frontend junit tests}"       # upload test log with exit code
+      - name: assert success
+        run: |
+          if [ $(cat jest/jest.exit-code) != 0 ]; then cat jest/jest.log && exit 1; fi                    # print frontend log and exit if frontend failed
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: jest-logs
+          path: jest/jest.log
 
   test-frontend:
     name: test (frontend)
