adding comments

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -42,16 +42,16 @@ jobs:
           docker buildx build -t tests .
       - name: publish results
         run: |
-          docker run --rm -v "$(pwd)/junit:/reports" tests          
-          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;
-          testspace "[junit/foo]junit/foo/junit.log{$(cat junit/foo/junit.exit-code):foo junit tests}"
-          testspace "[junit/bar]junit/bar/junit.log{$(cat junit/bar/junit.exit-code):bar junit tests}"
-          testspace "[junit/baz]junit/baz/junit.log{$(cat junit/baz/junit.exit-code):baz junit tests}"
+          docker run --rm -v "$(pwd)/junit:/reports" tests                                                # extracting test results from docker image
+          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;                                     # upload all junit xml's to testspace 
+          testspace "[junit/foo]junit/foo/junit.log{$(cat junit/foo/junit.exit-code):foo junit tests}"    # upload foo log with exit code 
+          testspace "[junit/bar]junit/bar/junit.log{$(cat junit/bar/junit.exit-code):bar junit tests}"    # upload bar log with exit code
+          testspace "[junit/baz]junit/baz/junit.log{$(cat junit/baz/junit.exit-code):baz junit tests}"    # upload baz log with exit code
       - name: assert success
         run: |
-          if [ $(cat junit/foo/junit.exit-code) != 0 ]; then cat junit/foo/junit.log && exit 1; fi
-          if [ $(cat junit/bar/junit.exit-code) != 0 ]; then cat junit/bar/junit.log && exit 1; fi
-          if [ $(cat junit/baz/junit.exit-code) != 0 ]; then cat junit/baz/junit.log && exit 1; fi
+          if [ $(cat junit/foo/junit.exit-code) != 0 ]; then cat junit/foo/junit.log && exit 1; fi        # print foo log and exit if foo failed
+          if [ $(cat junit/bar/junit.exit-code) != 0 ]; then cat junit/bar/junit.log && exit 1; fi        # print bar log and exit if foo failed
+          if [ $(cat junit/baz/junit.exit-code) != 0 ]; then cat junit/baz/junit.log && exit 1; fi        # print baz log and exit if foo failed
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
